### ISSUE TITLE
Transfer docs to grassroutes repo

### ISSUE THREAD

**Issue by hunterjsb** [Super-Sod/grassroutes-docs#1]
should go in a folder called `docs` in [grassroutes](https://github.com/orgs/Super-Sod/grassroutes)

**Comment by KLong57** [comment]
Taking this on!

**Comment by hunterjsb** [comment]
Yeah I think we should replace the readme in grassroutes with the one in grassroutes-docs, then make a `docs` folder in the root directory of grassroutes, and that's where we can put the other (preload) readme from the grassroutes-docs repo before archiving it. We can put the readme that we're replacing in /docs too and call it readme_old.md lol

**Comment by KLong57** [comment]
Sounds good made a pr on the grassroutes repo. Closing this and moving the issue.
